spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  mvc:
    problemdetails:
      enabled: false

  application:
    name: bytebank-transactions

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        hc5:
          enabled: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8083
  shutdown: graceful
  address: 0.0.0.0

resilience4j:
  circuitbreaker:
    instances:
      account-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${HOSTNAME}

logging:
  structured:
    format:
      file: logstash
  file:
    name: /tmp/transactions.json

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false