spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  mvc:
    problemdetails:
      enabled: false
  application:
    name: bytebank-transactions
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        hc5:
          enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
        batch.size: 32768
        compression.type: snappy
        spring.json.type.mapping: transaction-created:br.com.bytebank.transactions.infrastructure.messaging.kafka.event.TransactionCreatedEvent

    consumer:
        group-id: fraud-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        auto-offset-reset: latest
        enable-auto-commit: false
        properties:
          spring.json.trusted.packages: "*"
          max.poll.records: 50
          max.poll.interval.ms: 300000
          spring.json.type.mapping: score.response:br.com.bytebank.transactions.infrastructure.messaging.kafka.event.FraudScoreEvent
    listener:
        ack-mode: MANUAL_IMMEDIATE

server:
  port: 8083
resilience4j:
  circuitbreaker:
    instances:
      account-service:
        sliding-window-size: 10  # avalia as últimas 10 chamadas
        minimum-number-of-calls: 5
        failure-rate-threshold: 50        # abre o circuito se 50% falharem
        wait-duration-in-open-state: 30s  # fica bloqueado por 30s
        permitted-number-of-calls-in-half-open-state: 3
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  structured:
    format:
      file: logstash
  file:
    name: logs/transactions.json
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
bytebank:
  transactions:
    retry:
      max-attempts: 5
      deposit-delay-ms: 300000 #  5 minutes
      withdraw-delay-ms: 60000 # 1 minute
      transfer-delay-ms: 60000 # 1 minute

kind: Application